spring:
  datasource:
    initialize: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
bip.framework.security.opa:
  enabled: false # OPAEnablement: Set this to true if you want to enable OPA