{{- if not .Values.consul.secret -}}
{{- $fullName := include "bip-archetypetestconfig.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "bip-archetypetestconfig.name" . }}
    chart: {{ template "bip-archetypetestconfig.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  consul-acl-token: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
