{{- if not .Values.consul.secret -}}
{{- $fullName := include "bip-reference-person.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "bip-reference-person.name" . }}
    chart: {{ template "bip-reference-person.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{ .Values.consul.secretKey | default "consul-acl-token" }}: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
