{{- if (.Values.opa.enabled) -}}
{{- $fullName := include "bip-reference-person.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-kafka-keystore
  labels:
    app: {{ template "bip-reference-person.name" . }}
    chart: {{ template "bip-reference-person.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
binaryData:
  keystore: |-
  {{ .Files.Get .Values.kafka.keystore | b64enc | indent 4 }}
  {{- end }}