{{- $fullName := include "bip-archetypetest.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-kafka-keystore
  labels:
    app: {{ template "bip-archetypetest.name" . }}
    chart: {{ template "bip-archetypetest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
binaryData:
  keystore: |-
{{ .Files.Get .Values.kafka.keystore | b64enc | indent 4 }}
{{- end }}
