---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease #Custom Object type for use with Flux Helm Operator
metadata:
  name: bip-archetypetestconfig-ui-dev #Name of the object
  namespace: archetypetest-dev #Namespace in which to install the helmrelease object
  annotations:
    flux.weave.works/automated: "true" #Set this to true to automate installation/updating of this release when the Chart of this object changes
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: bip-archetypetestconfig-ui-dev #Name of the Helm release
  targetNamespace: archetypetest-dev #Namespace  in which to install the chart

  ########################################################################
  # Values section defines the location of the chart
  # This example pulls the chart from a Git repository
  ########################################################################
  chart:
    git: https://github.com/department-of-veterans-affairs/bip-vetservices-archetypetest-config #Repository where the pull the chart from
    ref: development #Branch or tag to retreive the chart from
    path: charts/bip-archetypetestconfig-ui #Path to the chart directory in the repository

  ########################################################################
  # Values section defines the parameters to the chart
  # These are specific to the chart being installed
  ########################################################################
  values:
    # ui.enabled
    #   Set to false when UI app deployment is not ready or not intended
    #   Tenant would then switch to true when UI app is ready to deploy
    ui:
      enabled: false # UIEnablement
    ingress:
      enabled: true
      hosts:
      - bip-archetypetestconfig-ui-dev.dev.bip.va.gov
      annotations:
      path: /
      tls:
        - secretName: bip-archetypetestconfig-ui-dev
        - hosts:
          - bip-archetypetestconfig-ui-dev.dev.bip.va.gov
    image:
      repository: container-registry.dev.bip.va.gov/archetypetest/bip-archetypetestconfig-ui
      tag: dev-df1e34c1ee08c104334b2219bbe58350bb8df02a
      pullPolicy: Always
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 750m
        memory: 1Gi
    certs:
      import: true
    react:
      bssUrl: https://bss-dev.dev.bip.va.gov/auth/
      brpUrl: https://blue.dev.bip.va.gov
      originUrl: https://bip-archetypetestconfig.archetypetest-dev.dev.bip.va.gov
      realm: idp
      clientId: bip-archetypetestconfig-ui-dev
      jwtDomains: https://blue.dev.bip.va.gov,https://bip-archetypetestconfig.archetypetest-dev.dev.bip.va.gov