apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-{{ .Values.cluster }}-archetypetest-jenkins-jobs
  labels:
    app: {{ template "jenkins-config.name" . }}
    chart: {{ template "jenkins-config.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $val := .Values.jenkinsJobs }}
  {{ $key }}: |-
{{ tpl $val $| indent 4 }}
{{- end }}