---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease #Custom Object type for use with Flux Helm Operator
metadata:
  name: jenkins-config #Name of the object
  namespace: archetypetest-dev #Namespace in which to install the helmrelease object
  annotations:
    flux.weave.works/automated: "true" #Set this to true to automate installation/updating of this release when the Chart of this object changes
spec:
  releaseName: jenkins-config #Name of the Helm release
  targetNamespace: archetypetest-dev #Namespace  in which to install the chart

  ########################################################################
  # Values section defines the location of the chart
  # This example pulls the chart from a Git repository
  ########################################################################
  chart:
    git: ssh://git@github.ec.va.gov/EPMO/bip-archetypetest-config #Repository where the pull the chart from
    ref: development #Branch or tag to retreive the chart from
    path: charts/jenkins-config #Path to the chart directory in the repository
  values:
    jenkinsConfig:
      globalLibrary: |
        unclassified:
          globalLibraries:
            libraries:
            - name: "jenkins-library"
              defaultVersion: "development"
              implicit: true
              retriever:
                modernSCM:
                  scm:
                    git:
                      credentialsId: "github"
                      remote: "https://github.ec.va.gov/EPMO/bip-jenkins-lib.git"
                      traits:
                      - "branchDiscoveryTrait"
      zzzz-alphatical-override-additionalSlaves: |
        jenkins:
          clouds:
            - kubernetes:
                name: kubernetes
                serverUrl: "https://kubernetes.default"
                namespace: "archetypetest-dev"
                jenkinsUrl: "http://dev8-archetypetest-jenkins:8080"
                jenkinsTunnel: "dev8-archetypetest-jenkins-agent:50000"
                templates:
                  - name: "fortify-sca"
                    label: "fortify-sca"
                    nodeUsageMode: EXCLUSIVE
                    inheritFrom: "default"
                    containers:
                      - name: jnlp
                        image: "container-registry.dev8.bip.va.gov/ci/jenkins-slave-fortify:20.1.0"
                        alwaysPullImage: false
                        workingDir: "/home/jenkins"
                        command: ""
                        args: "^${computer.jnlpmac} ^${computer.name}"
    jenkinsPlugins:
      plugins.txt: |
        blueocean-commons:1.23.2
        scriptler:3.1
        blueocean-rest:1.23.2
        token-macro:2.12
        blueocean-core-js:1.23.2
        cucumber-reports:5.3.0
        blueocean-web:1.23.2
        jenkins-design-language:1.23.2
        blueocean-dashboard:1.23.2
        mailer:1.32
#      pluginProperties.yaml: |
#        pluginAction: merge
    jenkins_framework_library: "https://github.ec.va.gov/EPMO/bip-jenkins-lib.git"
    github_apiurl: "https://github.ec.va.gov/api/v3"
    jenkins_framework_library_branch: master
    jenkins_framework_library_owner: EPMO
    jenkins_framework_library_repo: "bip-jenkins-lib"
    jenkins_project_repo_owner: EPMO
    jenkinsJobs:
      bip-archetypetest: |-
        <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject plugin="workflow-multibranch@2.21">
        <actions/>
        <description/>
        <properties>
        <org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty plugin="kubernetes@1.20.0">
        <permittedClouds/>
        </org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty>
        <org.jenkinsci.plugins.pipeline.maven.MavenConfigFolderOverrideProperty plugin="pipeline-maven@3.8.2">
        <settings class="jenkins.mvn.DefaultSettingsProvider"/>
        <globalSettings class="jenkins.mvn.DefaultGlobalSettingsProvider"/>
        <override>false</override>
        </org.jenkinsci.plugins.pipeline.maven.MavenConfigFolderOverrideProperty>
        <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.5.1">
        <dockerLabel/>
        <registry plugin="docker-commons@1.16"/>
        </org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig>
        </properties>
        <folderViews class="jenkins.branch.MultiBranchProjectViewHolder" plugin="branch-api@2.5.5">
        <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
        </folderViews>
        <healthMetrics>
        <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@6.10.1">
        <nonRecursive>false</nonRecursive>
        </com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric>
        </healthMetrics>
        <icon class="jenkins.branch.MetadataActionFolderIcon" plugin="branch-api@2.5.5">
        <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
        </icon>
        <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@6.10.1">
        <pruneDeadBranches>true</pruneDeadBranches>
        <daysToKeep>-1</daysToKeep>
        <numToKeep>-1</numToKeep>
        </orphanedItemStrategy>
        <triggers>
        <com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger plugin="cloudbees-folder@6.10.1">
        <spec>H/5 * * * *</spec>
        <interval>900000</interval>
        </com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger>
        </triggers>
        <disabled>false</disabled>
        <sources class="jenkins.branch.MultiBranchProject$BranchSourceList" plugin="branch-api@2.5.5">
        <data>
        <jenkins.branch.BranchSource>
        <source class="org.jenkinsci.plugins.github_branch_source.GitHubSCMSource" plugin="github-branch-source@2.6.0">
        <id>95f4fcda-912d-41eb-b373-bb865db31478</id>
        <apiUri>https://github.ec.va.gov/api/v3</apiUri>
        <credentialsId>github</credentialsId>
        <repoOwner>EPMO</repoOwner>
        <repository>Bip-archetypetest</repository>
        <repositoryUrl>https://github.ec.va.gov/EPMO/Bip-archetypetest</repositoryUrl>
        <traits>
        <org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
        <strategyId>1</strategyId>
        </org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
        <org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
        <strategyId>1</strategyId>
        </org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
        <org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait>
        <strategyId>1</strategyId>
        <trust class="org.jenkinsci.plugins.github_branch_source.ForkPullRequestDiscoveryTrait$TrustPermission"/>
        </org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait>
        <jenkins.scm.impl.trait.RegexSCMHeadFilterTrait plugin="scm-api@2.6.3">
        <regex>(master|development|PR-.*)</regex>
        </jenkins.scm.impl.trait.RegexSCMHeadFilterTrait>
        </traits>
        </source>
        <strategy class="jenkins.branch.DefaultBranchPropertyStrategy">
        <properties class="empty-list"/>
        </strategy>
        </jenkins.branch.BranchSource>
        </data>
        <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
        </sources>
        <factory class="org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory">
        <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
        <scriptPath>Jenkinsfile</scriptPath>
        </factory>
        </org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject>