---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease #Custom Object type for use with Flux Helm Operator
metadata:
  name: bip-archetypetest-uat #Name of the object
  namespace: archetypetest-ivv #Namespace in which to install the helmrelease object
  annotations:
    flux.weave.works/automated: "true" #Set this to true to automate installation/updating of this release when the Chart of this object changes
    flux.weave.works/tag.chart-image: glob:uat-* #Regex value flux will look for in image tag to auto update

spec:
  releaseName: bip-archetypetest-uat #Name of the Helm release
  targetNamespace: archetypetest-uat #Namespace in which to deploy chart

  ########################################################################
  # Values section defines the location of the chart
  # This example pulls the chart from a Git repository
  ########################################################################
  chart:
    git: ssh://git@github.ec.va.gov/EPMO/bip-archetypetest-config #Repository where the pull the chart from
    ref: staging #Branch or tag to retrieve the chart from
    path: charts/bip-archetypetest #Path to the chart directory in the repository

  ########################################################################
  # Values section defines the parameters to the chart
  # These are specific to the chart being installed
  ########################################################################
  values:
    # kubernetes ingress configuration
    ingress:
      enabled: true
      hosts:
        - bip-archetypetest.archetypetest-uat.stage8.bip.va.gov
      annotations:
        # kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      path: /
      tls:
      - secretName: bip-archetypetest-uat-tls
        hosts:
          - bip-archetypetest.archetypetest-uat.stage8.bip.va.gov
    # kong ingress configuration
    kong:
      ingress:
        anonymous:
          enabled: false
          hosts:
            - name: bip-archetypetest.archetypetest-uat.apps.stage8.bip.va.gov
              paths:
                - /
          annotations:
            kubernetes.io/ingress.class: kong-internal
            kubernetes.io/tls-acme: "true"
            plugins.konghq.com: archetypetest-uat.bip-archetypetest-uat.acl, archetypetest-uat.bip-archetypetest-uat.jwt.anonymous
          tls:
            - secretName: bip-archetypetest-uat-tls
              hosts:
                - bip-archetypetest.archetypetest-uat.apps.stage8.bip.va.gov
        secured:
          enabled: false
          hosts:
            - name: bip-archetypetest.archetypetest-uat.apps.stage8.bip.va.gov
              paths:
                - /api/v.+/resourcename
          annotations:
            kubernetes.io/ingress.class: kong-internal
            kubernetes.io/tls-acme: "true"
            plugins.konghq.com: archetypetest-uat.bip-archetypetest-uat.acl, archetypetest-uat.bip-archetypetest-uat.jwt
            configuration.konghq.com: bip-archetypetest-uat-kongingress
          tls:
            - secretName: bip-archetypetest-uat-tls
              hosts:
                - bip-archetypetest.archetypetest-uat.apps.stage8.bip.va.gov
    image:
      repository: container-registry.stage8.bip.va.gov/archetypetest/bip-archetypetest
      tag: 0.0.2-SNAPSHOT
    opaImage:
      repository: container-registry.stage8.bip.va.gov/openpolicyagent/opa
    consul:
      config:
        enabled: true
        prefix: config/archetypetest/uat
      discovery:
        enabled: true
        register: false
      secret: consul-acl-token
      host: stage8-consul-helm-server.vault.svc.stage8
      scheme: http
    vault:
      enabled: true
      host: stage8-vault.vault.svc.stage8
      kubernetes:
        role: archetypetest-read
      kv:
        applicationName: archetypetest/bip-archetypetest
      port: 8200
      scheme: http
    spring:
      profiles: dev
