bip.framework.security:
  http:
    cors:
      enabled: true
  opa:
    enabled: true
    allVotersAbstainGrantAccess: false
        
spring:
  kafka:
    consumer:
      enabled: true
    properties:
      security:
        protocol: SSL
      ssl:
        enabled:
          protocols: TLSv1.3,TLSv1.2,TLSv1.1,TLSv1
        keystore:
          location: /kafka/keystore/keystore
          password: ${blue.bip.va.gov.keyStorePass}
        truststore:
          location: /kafka/truststore/truststore
          password: ${blue.bip.va.gov.trustStorePass}
      bootstrap:
        servers: SSL://kafka.sbx.bip.va.gov:443
      schema:
        registry:
          url: https://schemaregistry.confluentv2.svc.dev8:8081
    streams:
      enabled: false
      properties:
        bootstrap.servers: SSL://kafka.sbx.bip.va.gov:443
      
bip:
  framework:
    localstack:
      enabled: false
    aws:
      sns:
        enabled: false
      sqs:
        enabled: false
      s3:
        enabled: false
    kong:
      enabled: false
      
bip-archetypetest:
  origins: #This will be replaced with archetypetests but we have to obfuscate it to prevent overriding with artifact name
    - https://bip-archetypetest-ui-dev.dev8.bip.va.gov
    - https://archetypetest-dev.dev8.bip.va.gov
    - http://localhost:3000
