spring:
  cache:
    type: simple
  kafka:
    consumer:
      enabled: false
    properties:
      security:
        protocol: SSL
      ssl:
        enabled:
          protocols: TLSv1.2,TLSv1.1,TLSv1
        keystore:
          location: /kafka/keystore/keystore
          password: ${blue.bip.va.gov.keyStorePass}
        truststore:
          location: /kafka/truststore/truststore
          password: ${blue.bip.va.gov.trustStorePass}
      bootstrap:
        servers: SSL://kafka.sbx.bip.va.gov:443
      schema:
        registry:
          url: https://schemaregistry.confluentv2.svc.dev8:8081
    streams:
      enabled: false
      properties:
        bootstrap.servers: SSL://kafka.sbx.bip.va.gov:443

bip:
  framework:
    security:
      opa:
        enabled: true
        allVotersAbstainGrantAccess: false
      actuator:
        username: bluebuilder
        password: 2GiuQ1LKWS5y
    localstack:
      enabled: false
    aws:
      sns:
        enabled: false
      sqs:
        enabled: false
      s3:
        enabled: false
