---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease #Custom Object type for use with Flux Helm Operator
metadata:
  name: bip-archetypetestconfig-prodtest #Name of the object
  namespace: archetypetest-perf #Namespace in which to install the Chart
  annotations:
    flux.weave.works/automated: "true" #Set this to true to automate installation/updating of this release when the Chart of this object changes
    flux.weave.works/tag.chart-image: glob:prodtest-* #Regex value flux will look for in image tag to auto update
spec:
  releaseName: bip-archetypetestconfig-prodtest #Name of the Helm release
  targetNamespace: archetypetest-prodtest #Namespace in which to install the chart

  ########################################################################
  # Values section defines the location of the chart
  # This example pulls the chart from a Git repository
  ########################################################################
  chart:
    git: https://github.com/department-of-veterans-affairs/bip-vetservices-archetypetest-config #Repository where the pull the chart from
    ref: master #Branch or tag to retrieve the chart from
    path: charts/bip-archetypetestconfig #Path to the chart directory in the repository

  ########################################################################
  # Values section defines the parameters to the chart
  # These are specific to the chart being installed
  ########################################################################
  values:
    # kubernetes ingress configuration
    ingress:
      enabled: true
      hosts:
        - bip-archetypetestconfig.archetypetest-prodtest.prod.bip.va.gov
      annotations:
      path: /
      tls:
        - secretName: bip-archetypetestconfig-prodtest-tls
        - hosts:
            - bip-archetypetestconfig.archetypetest-prodtest.prod.bip.va.gov
    # kong ingress configuration
    kong:
      ingress:
        anonymous:
          enabled: false
          hosts:
            - name: bip-archetypetestconfig.archetypetest-prodtest.apps.prod.bip.va.gov
              paths:
                - /
          annotations:
            kubernetes.io/ingress.class: kong-internal
            kubernetes.io/tls-acme: "true"
            plugins.konghq.com: archetypetest-prodtest.bip-archetypetestconfig-prodtest.acl, archetypetest-prodtest.bip-archetypetestconfig-prodtest.jwt.anonymous
          tls:
            - secretName: bip-archetypetestconfig-prodtest-tls
            - hosts:
                - bip-archetypetestconfig.archetypetest-prodtest.apps.prod.bip.va.gov
        secured:
          enabled: false
          hosts:
            - name: bip-archetypetestconfig.archetypetest-prodtest.apps.prod.bip.va.gov
              paths:
                - /api/v.+/resourcename
          annotations:
            kubernetes.io/ingress.class: kong-internal
            kubernetes.io/tls-acme: "true"
            plugins.konghq.com: archetypetest-prodtest.bip-archetypetestconfig-prodtest.acl, archetypetest-prodtest.bip-archetypetestconfig-prodtest.jwt
            configuration.konghq.com: bip-archetypetestconfig-prodtest-kongingress
          tls:
            - secretName: bip-archetypetestconfig-prodtest-tls
            - hosts:
                - bip-archetypetestconfig.archetypetest-prodtest.apps.prod.bip.va.gov
    image:
      repository: container-registry.prod.bip.va.gov/archetypetest/bip-archetypetestconfig
      tag: 0.0.2-SNAPSHOT
    opaImage:
      repository: container-registry.prod.bip.va.gov/openpolicyagent/opa
    consul:
      enabled: true
      config:
        enabled: true
        prefix: config/archetypetest/prodtest
      discovery:
        enabled: true
        register: false
      secret: consul-acl-token
      scheme: http
    vault:
      enabled: true
      host: vault.vault
      kubernetes:
        role: archetypetest-read
      kv:
        applicationName: archetypetest/bip-archetypetestconfig
      port: 8200
      scheme: http
    spring:
      profiles: prodtest
    hpa:
      enabled: false
      cpu: 100
      maxReplicas: 2