spring:
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
management:
  health:
    consul:
      enabled: false
    vault:
      enabled: false
    db:
      enabled: false
    diskspace:
      enabled: false
    refresh:
      enabled: false
    ratelimiters:
      enabled: false
    circuitbreakers:
      enabled: false
    hystrix:
      enabled: false