# kubernetes ingress configuration
ingress:
  enabled: true
  hosts:
    - bip-archetypetest.archetypetest-prodtest.prod.bip.va.gov
  annotations:
  path: /
  tls:
    - secretName: bip-archetypetest-prodtest-tls
    - hosts:
        - bip-archetypetest.archetypetest-prodtest.prod.bip.va.gov
# kong ingress configuration
kong:
  ingress:
    anonymous:
      enabled: false
      hosts:
        - name: bip-archetypetest.archetypetest-prodtest.apps.prod.bip.va.gov
          paths:
            - /
      annotations:
        kubernetes.io/ingress.class: kong-internal
        kubernetes.io/tls-acme: "true"
        plugins.konghq.com: archetypetest-prodtest.bip-archetypetest-prodtest.acl, archetypetest-prodtest.bip-archetypetest-prodtest.jwt.anonymous
      tls:
        - secretName: bip-archetypetest-prodtest-tls
        - hosts:
            - bip-archetypetest.archetypetest-prodtest.apps.prod.bip.va.gov
    secured:
      enabled: false
      hosts:
        - name: bip-archetypetest.archetypetest-prodtest.apps.prod.bip.va.gov
          paths:
            - /api/v.+/resourcename
      annotations:
        kubernetes.io/ingress.class: kong-internal
        kubernetes.io/tls-acme: "true"
        plugins.konghq.com: archetypetest-prodtest.bip-archetypetest-prodtest.acl, archetypetest-prodtest.bip-archetypetest-prodtest.jwt
        configuration.konghq.com: bip-archetypetest-prodtest-kongingress
      tls:
        - secretName: bip-archetypetest-prodtest-tls
        - hosts:
            - bip-archetypetest.archetypetest-prodtest.apps.prod.bip.va.gov
image:
  repository: container-registry.prod.bip.va.gov/archetypetest/bip-archetypetest
  tag: 0.0.2-SNAPSHOT
opaImage:
  repository: container-registry.prod.bip.va.gov/openpolicyagent/opa
consul:
  enabled: true
  config:
    enabled: true
    prefix: config/archetypetest/prodtest
  discovery:
    enabled: true
    register: false
  secret: consul-acl-token
  scheme: http
vault:
  enabled: true
  host: vault.vault
  kubernetes:
    role: archetypetest-read
  kv:
    applicationName: archetypetest/bip-archetypetest
  port: 8200
  scheme: http
spring:
  profiles: prodtest
hpa:
  enabled: false
  cpu: 100
  maxReplicas: 2