{{- if .Values.hpa.enabled -}}
{{ if and (eq (int64 .Capabilities.KubeVersion.Major) (int64 1)) (ge (int64 (.Capabilities.KubeVersion.Minor | trimSuffix "+")) (int64 25)) }}
apiVersion: autoscaling/v2beta2
{{ else }}
apiVersion: autoscaling/v1
{{ end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "bip-archetypetestconfig-ui.fullname" . }}-hpa
  #labels:
  #  app: {{ template "bip-archetypetestconfig-ui.name" . }}
  #  chart: {{ template "bip-archetypetestconfig-ui.chart" . }}
  #  release: {{ .Release.Name }}
  #  heritage: {{ .Release.Service }}
spec:
  {{ if and (eq (int64 .Capabilities.KubeVersion.Major) (int64 1)) (ge (int64 (.Capabilities.KubeVersion.Minor | trimSuffix "+")) (int64 25)) }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.scaleDownStabilizationWindowSeconds }}
  {{ end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "bip-archetypetestconfig-ui.fullname" . }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      {{ if and (eq (int64 .Capabilities.KubeVersion.Major) (int64 1)) (ge (int64 (.Capabilities.KubeVersion.Minor | trimSuffix "+")) (int64 25)) }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpu }}
      {{ else }}
      targetAverageUtilization: {{ .Values.hpa.cpu }}
      {{ end }}
  {{- end }}
  {{- if .Values.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .Values.hpa.memory }}
  {{- end }}
{{- end }}
