{{- if (.Values.ui.enabled) -}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bip-archetypetestconfig-ui.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{ if and (eq (int64 .Capabilities.KubeVersion.Major) (int64 1)) (ge (int64 (.Capabilities.KubeVersion.Minor | trimSuffix "+")) (int64 16)) }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "bip-archetypetestconfig-ui.name" . }}
    chart: {{ template "bip-archetypetestconfig-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{ if and (eq (int64 .Capabilities.KubeVersion.Major) (int64 1)) (ge (int64 (.Capabilities.KubeVersion.Minor | trimSuffix "+")) (int64 16)) }}
  ingressClassName: nginx
  {{ end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName | default "genericCert" }}
  {{- end }}
{{- end }}

  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
            {{ if and (eq (int64 $.Capabilities.KubeVersion.Major) (int64 1)) (ge (int64 ($.Capabilities.KubeVersion.Minor | trimSuffix "+")) (int64 16)) }}
              service:
                name: {{ $fullName }}
                port:
                  name: http
            pathType: ImplementationSpecific
            {{ else }}
              serviceName: {{ $fullName }}
              servicePort: 80
            {{ end }}
  {{- end }}
{{- end }}
{{- end }}
